name: 提取alpine版cloudreve
on:
  workflow_dispatch:
  schedule:
   - cron: 0 0 */1 * *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: cloudreve/cloudreve:latest
          path: /cloudreve/cloudreve
      - name: strip
        run: |
          sudo apt-get update
          sudo apt-get -y install jq
          strip ${{ steps.extract.outputs.destination }}/cloudreve
          RESULT=$(curl -k -s https://hub.docker.com/v2/repositories/cloudreve/cloudreve/tags/?page_size=2)
          USER=$(echo ${RESULT} | jq  '.results[1].name')
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: $USER
